Feature branch
DanisHaertdinov/SpotifyApiClient pull request #3
Opened 2020-12-04 07:00 UTC by DanisHaertdinov

2020-12-04 15:22 UTC, kicumkicum commented
Понятие `feature`-ветка предполагает нейимнг `feature/add-promise-examples`... подумал я. Но начал искать пример на базе gitflow и толком не нашел)) Но тут все дело в том, что префиксы воспринимаются гитом как директории с одной стороны (можешь найти их в .git проекта). С другой проще настраивать всякие правила ci/cd. Ну и общепринятых префиксов не так много `feature/, hotfix/, support/, release/` Но наверно на некоторых проектах могут быть и отличающиеся правила

2020-12-04 15:23 UTC, kicumkicum requested changes
Отлично получилось. Молодец. Несколько комментов пофиксить и можно лить.

2020-12-04 15:23 UTC, kicumkicum commented on src/labs/index.js
> +  api.getPlaylist(playlistId)
Прямо сейчас функцией `clonePlaylist` не очень удобно пользоваться, потому что в ней промис, но мы не сможем дождаться его исполнения. Понимаешь почему?

2020-12-04 15:23 UTC, kicumkicum commented on src/labs/index.js
> +        const requests = originalPlaylist.tracks.map((tracksGroup) => {
Проверь, что будет храниться в этой переменной `requests`

2020-12-04 15:23 UTC, kicumkicum commented on src/labs/index.js
> +  return new Promise((resolve) => setTimeout(() => resolve(), delay));
` setTimeout(() => resolve(), delay)` запиши это короче

2020-12-04 15:23 UTC, kicumkicum commented on src/api/api.js
> +  getPlaylistTracks(playlistId, limit = 100, offset = 0) {
А какое верхнее значение для limit?

2020-12-04 15:23 UTC, kicumkicum commented on src/api/api.js
> +  getPlaylistTracks(playlistId, limit = 100, offset = 0) {
Или его нет?

2020-12-06 13:05 UTC, DanisHaertdinov commented on src/labs/index.js
> +  api.getPlaylist(playlistId)
Да, думаю, что если добавить return перед самым первым запросом, то-есть возвращать этот промис, на функцию можно будет подписаться и точно знать когда она закончила работу.

2020-12-06 13:06 UTC, DanisHaertdinov commented on src/api/api.js
> +  getPlaylistTracks(playlistId, limit = 100, offset = 0) {
100

2020-12-06 14:21 UTC, DanisHaertdinov commented on src/labs/index.js
> +        const requests = originalPlaylist.tracks.map((tracksGroup) => {
Забыл вернуть промис.

2020-12-06 15:50 UTC, DanisHaertdinov commented on src/labs/index.js
> +  return new Promise((resolve) => setTimeout(() => resolve(), delay));
done

2020-12-09 18:32 UTC, kicumkicum approved these changes

2020-12-09 18:32 UTC, kicumkicum commented on src/api/api.js
> +  getPlaylistTracks(playlistId, limit = 100, offset = 0) {
Если снаружи передать 101, то оно уйдет на сервер

2020-12-09 18:33 UTC, kicumkicum commented
О, я мержить не могу. Сделай это ты

2020-12-10 06:33 UTC, merged